Algoritmo "Exercicio07"
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição : Escreva um algoritmo para ler as dimensões de um retângulo (base e altura), calcular e escrever a área do retângulo.
// Autor(a) : Pedro
// Data atual : 24/08/2021
Var
bas,alt,a:real


Inicio
escreva("Informe a base : ")
leia(alt)
escreval("informe a altura: ")
leia(bas)
a<- alt * bas
escreval("A area do retangulo é: ",a)


Fimalgoritmo