     Algoritmo "Exercicio08"
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição : Escreva um algoritmo para ler a area do circulo, calcular e escrever a área do retângulo.
// Autor(a) : Pedro
// Data atual : 24/08/2021
Var
lag,res:real

Inicio
Escreval("Informe a largura do circulo ")
leia(lag)
res<- (lag/2)^2 *pi

escreva("A area do circulo é" ,res)

Fimalgoritmo