Algoritmo "contar numeros pares"
// Disciplina   : [Java Script e Lógica de Programação]
// Professor   : Jailson
// Descrição   : contar numeros pares
// Autor(a)    : Pedro Rocha
// Data atual  : 01/09/2021
Var
   n1,total,cont:inteiro


Inicio

   enquanto cont<500 faca
      cont<-cont+1
      n1<-n1+1

      se(n1%2=0) entao
         total<-n1+total
      fimse
   fimenquanto

    escreva( "a soma dos numeros pares é",total)

Fimalgoritmo