Algoritmo "Exemplo Laco Para"
// Disciplina : [Java Script e Logica de Programação ]
// Professor : Jailson Costa dos Santos
// Descrição : exemplo de laço de repetição
// Autor(a) : Pedro Rocha
// Data atual : 03/09/2021
Var
// Seção de Declarações das variáveis
cont:inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para cont de 1 ate 10 passo 1 faca
Escreval("Osasco terror da Oeste")
fimpara



Fimalgoritmo