Algoritmo "EXERCICIO 10"
// Disciplina   : [Java Script e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Calcula o custo real do carro baseado em seu custo de fábrica, da porcentagem do distribuidor e do imposto.
// Autor(a)    : Pedro Rocha
// Data atual  : 25/08/2021
Var
carro,total:real


Inicio
Escreva("Quanto vale o carro?")
leia(carro)
total<- (28/100*carro)+(45/100*carro+carro)
escreva("O carro vai custar R$",total)


Fimalgoritmo