Algoritmo "Exercicio68"
// Disciplina   : [Java Script e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Apresentar o total da soma obtida dos cem primeiros números inteiros (1+2+3+4+...+98+99+100).
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2021
Var
total,cont:inteiro
Inicio

para cont de 1 ate 100 passo 1 faca
total<-cont+total
fimpara
Escreva("A somatória dos cem primeiros numeros é", total)


Fimalgoritmo