Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/08/2021
Var
sal,porc,total:real


Inicio
escreval("Qual o seu salario? ")
leia(sal)
escreval("Qual o Seu porcentual de reajuste? ")
leia(porc)
total<-(porc/100)*sal+sal
escreva("Seu salario vai ser: ",total)


Fimalgoritmo