Algoritmo "oi"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2021
Var
   cont,total:inteiro


Inicio


   repita
      se CONT%2=0 entao
         total<-total+cont
      fimse
      cont<-cont+1
   ate (cont>500)
   Escreval(total)

Fimalgoritmo