Algoritmo "EXERCICIO23"
// Disciplina   : [Java Script e Lógica de Programação]
// PROFESSOR:     Jailson
// Descrição   : IMC
// Autor(a)    : Pedro Rocha
// Data atual  : 26/08/2021
Var
nome,sexo:CARACTERE
peso_ideal:real


Inicio

ESCREVA("QUAL O SEU NOME? ")
LEIA(nome)
ESCREVA("QUAL O SEU SEXO? ")
LEIA(sexo)
se (sexo=M) ENTAO
peso_ideal <- (72.7 * altura) - 58
senão
peso_ideal <- (62.1 * altura) – 44.7
 fimse
escreval ("O peso ideal para você é "peso_ideal)
fim

Fimalgoritmo