Algoritmo "EXERCICIO15"
// Disciplina   : [Java Script e Lógica de Programação]
// Professor   : Obama
// Descrição   : VERIFICAR SE O NUMERO É POSITIVO OU NEGATIVO
// Autor(a)    : Pedro Rocha Cardoso da Silva
// Data atual  : 25/08/2021
Var
numBER:inteiro


Inicio
    ESCREVA("DIGITE UM NUMERO: ")
    LEIA(NUMBER)
    SE (NUMBER<0) ENTAO
    ESCREVAL("O NUMERO É NEGATIVO !")
    SENAO
    ESCREVAL("O NUMERO É POSITIVO !")
    FIMSE

Fimalgoritmo