Algoritmo "eXERCICIOASDS"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2021
Var
// Seção de Declarações das variáveis 
x,r,cont:inteiro

Inicio
CONT<-1
REPITA
Escreva("Informe o X: ")
leia(X)
R<-X*3
cont<-cont+1
ate(cont>5)
Escreva(R)


Fimalgoritmo