Algoritmo "EXERCICIO12"
// Disciplina   : [Java Script e Lógica de Programação]
// Professor   : Pedro Rocha
// Descrição   : Converte a temperatura de celsius para fahrenheit
// Autor(a)    :Pedro Rocha
// Data atual  : 25/08/2021
Var
tc, tf: real




Inicio
escreval("Conversor de temperaturas")



escreval("Informe o valor da temperatura a ser convertida(ºC)")
leia(tc)



tf<- (tc * 1.8) + 32



escreval(tc, "ºC é igual à", tf, " ºF")



Fimalgoritmo