Algoritmo "EXERCICIO19"

// Disciplina   : [Java Script e Lógica de Programação]
// Professor   : JAILSON
// Descrição   :DEFINIR QUAL O NUMERO É MAIOR
// Autor(a)    :Pedro Rocha
// Data atual  : 25/08/2021
Var
   NUM,NUM2:REAL

Inicio
   ESCREVA("Informe um numero: ")
   Leia(num)
   ESCREVA("Informe outro numero: ")
   LEIA(NUM2)
   se(NUM>NUM2) ENTAO
      ESCREVAL(NUM," É maior que ",NUM2)
   senao
      ESCREVAL(NUM2," É maior que ",NUM)
   fimse

Fimalgoritmo