Algoritmo "Exercicio 48 manzano"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Pedro ocha
// Data atual  : 01/09/2021
Var
n1,total,cont:inteiro

Inicio
Escreval("A soma dos 100 primeiros numeros inteiros")
enquanto cont<100 faca
cont<-cont+1
n1<-n1+1
total<-total+n1
Escreval(total)
fimenquanto



Fimalgoritmo