Algoritmo "PROGRAMA DE SOMA"
// Disciplina   : [Java Script e Lógica de Programação]
// Professor   : Professor Obama
// Descrição    :Soma de dois O e apresentação do resultado
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2021
Var
n1,n2,soma:inteiro


Inicio
escreva("Digite  um valor: ")
leia(N1)
Escreval("Digite outro valor: ")
leia(N2)
soma<-N1+N2
Escreval("O resultado da soma é :",soma)


Fimalgoritmo