Algoritmo "Progrma de subtração"
// Disciplina   : Java Script e Lógica de Programação]
// Professor   : Antonio Ca Nicolodi
// Descrição   : Programa para subtrair valores
// Autor(a)    : Pedro rocha
// Data atual  : 24/08/2021
Var
n1,n2,res:real

Inicio
Escreva ("Digite uma valor: ")
Leia(n1)
Escreval("Digite outro valor: ")
Leia(n2)
res<-n1-n2
Escreval("O valor da subtração é: ",res)


Fimalgoritmo