Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/09/2021
Var
// Seção de Declarações das variáveis 
numero,cont:inteiro

Inicio
Escreva("Informe o valor: ")
leia(numero)
para cont de 1 ate 10 passo 1 faca
ESCREVAL("A TABUADA DO",NUMERO,"X",cont," É ",NUMERO*CONT)
fimpara



Fimalgoritmo